# Test site for verifying CSS tree-shaking
theme = "congo"
defaultContentLanguage = "en"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
